### ISSUE TITLE
[DOC] Add z and z-1 equations

### ISSUE THREAD

**Issue by luizvilla** [owntech-foundation/control_library#11]
**Description**

While using the library I came across the need to know the z and z-1 transfer functions of our controllers. 

**Action**

Add the z and z-1 transfer functions to all the controls and filters.

**Comment by rrodgeur** [comment]
The issue is closed with the commit docs@86bca353.

**Comment by pierre-haessig** [comment]
Direct link to the commit: https://github.com/owntech-foundation/control_library/commit/86bca353f67f117a748e24860df87b606bff75c3
